## **Lab 8 - A Dot product and a Matrix Multiplication in PyTorch and Tensorflow**
#### Name: **Chitrank Dave**
#### Student #: **8938766**

Imports

In [21]:
import torch
import tensorflow as tf

#### **1. PyTorch:**
##### - Calculate the dot product between two vectors each of length 3



In [22]:
vector_1 = torch.tensor([1, 2, 3, 4, 5, 6])
vector_2 = torch.tensor([7, 8, 9, 3, 2, 1])

torch.dot(vector_1, vector_2)

tensor(78)

##### - Calculate the matrix multiplication of two 2-dimensional matrices, each with a size of (2,2) 

In [23]:
mat_1 = torch.tensor([[1, 2],[3, 4]])
mat_2 = torch.tensor([[5, 6],[7, 8]])

torch.matmul(mat_1, mat_2)

tensor([[19, 22],
        [43, 50]])

#### **2. Tensorflow:**
##### - Calculate the dot product between the same vectors as above (re-define them in Tensorflow)



In [24]:
vector_1 = torch.tensor([1, 2, 3, 4, 5, 6])
vector_2 = torch.tensor([7, 8, 9, 3, 2, 1])

tf.tensordot(vector_1, vector_2, axes=1).numpy()

78

##### - Calculate the matrix multiplication of the same matrics as above (re-define them in Tensorflow) 

In [26]:
mat_1 = torch.tensor([[1, 2],[3, 4]])
mat_2 = torch.tensor([[5, 6],[7, 8]])

tf.matmul(mat_1, mat_2)

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[19, 22],
       [43, 50]])>